version: 0.2

phases:
  install:
    commands:
      - echo Installing...

  build:
    commands:
      - echo Creating zip file...
      - zip function.zip lambda_fun.py

artifacts:
  files:
    - function.zip
